CREATE TABLE `user` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(64) NOT NULL COMMENT '用户昵称',
    `phone_no` VARCHAR(32) NOT NULL COMMENT '',
    `email` VARCHAR(32) NOT NULL COMMENT '',
    `type` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '用户类型，1 顾客 2 卖主',
    `merchant_shop_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '店面 id 默认为 0',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';
